-- AlterTable
ALTER TABLE "Scan" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'queued';
ALTER TABLE "Scan" ADD COLUMN "totalPorts" INTEGER NOT NULL DEFAULT 65535;
ALTER TABLE "Scan" ADD COLUMN "scannedPorts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Scan" ADD COLUMN "openPorts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Scan" ADD COLUMN "error" TEXT;
ALTER TABLE "Scan" ADD COLUMN "startedAt" DATETIME;
ALTER TABLE "Scan" ADD COLUMN "finishedAt" DATETIME;
ALTER TABLE "Scan" ADD COLUMN "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Scan" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
