-- CreateTable
CREATE TABLE "Settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "scanEnabled" INTEGER NOT NULL DEFAULT 1,
    "scanIntervalMinutes" INTEGER NOT NULL DEFAULT 1440,
    "scanConcurrency" INTEGER NOT NULL DEFAULT 2,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
